name: learn-github-actions
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkut code
      - run: echo OK
        name: code build
      - run: echo OK
        name: code test
      - run: echo OK
        name: code review
      - run: echo OK
        name: release software

