name: learn-github-actions
on: [push]
jobs:
  ci-server:
    uses: pdevops78/github-reuse-actions/.github/workflows/ci-server.yml@main
    with:
      project_name: expense-frontend.yml
    secrets: inherit