name: learn-github-actions
on:
  push:
    tags:
      - '*'
jobs:
  release:
    uses: pdevops78/github-reuse-actions/.github/workflows/release.yml@main
    with:
      project_name: expense-frontend
      backend_release_archive: "static/ asset-manifest.json index.html VERSION"
    secrets: inherit